name = "Example"
uuid = "1936ec80-c5c6-4288-9ef9-39360b9ac87d"
authors = ["George Kopras"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
